apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: promecieus
  name: promecieus
  namespace: promecieus
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: promecieus:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: alerts
      uri: https://github.com/omertuc/promecieus
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: "GitHub"
    github:
      secret: "secret101"
